# Generated by Django 5.0.6 on 2024-07-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_statement',
        ),
        migrations.AddField(
            model_name='option',
            name='option_letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='main.option')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='main.question')),
            ],
        ),
    ]
