# Generated by Django 5.0.6 on 2024-08-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_option_is_correct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('number_of_questions', models.IntegerField(choices=[(10, '10'), (20, '20'), (30, '30')])),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('truefalse', 'True/False'), ('shortanswer', 'Short Answer')], max_length=20)),
                ('language', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French')], max_length=20)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
