# Generated by Django 5.0.6 on 2024-08-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('truefalse', 'True/False'), ('shortanswer', 'Short Answer'), ('matching', 'Matching'), ('mix', 'Mix')], max_length=20),
        ),
    ]
