# Generated by Django 5.0.6 on 2024-08-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mcqquestion_qno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswering',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
