# Generated by Django 5.0.6 on 2024-08-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_questionanswering_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswering',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
