# Generated by Django 5.0.6 on 2024-08-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_questionanswering_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truefalsequestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
