# Generated by Django 5.0.6 on 2024-08-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_fillintheblanksquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillintheblanksquestion',
            name='correct_answers',
            field=models.TextField(),
        ),
    ]
