# Generated by Django 5.0.6 on 2024-08-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_fillintheblanksquestion_qno_questionanswering_qno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillintheblanksquestion',
            name='qno',
            field=models.CharField(blank=True, default=10, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='qno',
            field=models.CharField(blank=True, default=10, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswering',
            name='qno',
            field=models.CharField(blank=True, default=10, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='qno',
            field=models.CharField(blank=True, default=10, max_length=100, null=True),
        ),
    ]
